server:
  port: 7084

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: demo-app
          uri: http://localhost:7083
          predicates:
            - Path=/demo/**

management:
  endpoints:
    web:
      exposure:
        include: '*'

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka